<?php

namespace Oveleon\ContaoPropstackApiBundle\Controller\Options;

class Constants
{
    /**
     * Webhook constants
     */
    const HOOK_CLIENT_CREATED = 'client_created';
    const HOOK_CLIENT_UPDATED = 'client_updated';
    const HOOK_PROPERTY_CREATED = 'property_created';
    const HOOK_PROPERTY_UPDATED = 'property_updated';
    const HOOK_TASK_CREATED = 'task_created';
    const HOOK_TASK_UPDATED = 'task_updated ';
    const HOOK_TASK_DELETED = 'task_deleted';
    const HOOK_CLIENT_PROPERTY_CREATED = 'client_property_created';
    const HOOK_CLIENT_PROPERTY_UPDATED = 'client_property_updated';
    const HOOK_CLIENT_PROPERTY_DELETED = 'client_property_deleted';
    const HOOK_PROJECT_CREATED = 'project_created';
    const HOOK_PROJECT_UPDATED = 'project_updated';
    const HOOK_DOCUMENT_CREATED = 'document_created';
    const HOOK_DOCUMENT_UPDATED = 'document_updated';
    const HOOK_DOCUMENT_DELETED = 'document_deleted';
    const HOOK_SAVED_QUERY_CREATED = 'saved_query_created';
    const HOOK_SAVED_QUERY_UPDATED = 'saved_query_updated';
    const HOOK_SAVED_QUERY_DELETED = 'saved_query_deleted';

    /**
     * Activity constants
     */
    const ACTIVITY_TYPE_MESSAGE = 'message';
    const ACTIVITY_TYPE_NOTE = 'note';
    const ACTIVITY_TYPE_REMINDER = 'reminder';
    const ACTIVITY_TYPE_EVENT = 'event';
    const ACTIVITY_TYPE_POLICY = 'policy';

    /**
     * Custom fields constants
     */
    const CUSTOM_FIELD_ENTITY_CLIENTS = 'for_clients';
    const CUSTOM_FIELD_ENTITY_PROPERTIES = 'for_properties';
    const CUSTOM_FIELD_ENTITY_PROJECTS = 'for_projects';
    const CUSTOM_FIELD_ENTITY_BROKERS = 'for_brokers';

    /**
     * Image constants
     */
    const IMAGE_TYPE_PROPERTY = 'Property';
    const IMAGE_TYPE_PROJECT = 'Project';

    /**
     * Unit constants
     */
    const MARKETING_TYPE_BUY = 'BUY';
    const MARKETING_TYPE_RENT = 'RENT';

    const USAGE_TYPE_LIVING = 'LIVING';
    const USAGE_TYPE_COMMERCIAL = 'COMMERCIAL';
    const USAGE_TYPE_INVESTMENT = 'INVESTMENT';

    const RELATIONSHIP_PARTNER = 'partner';
    const RELATIONSHIP_OWNER = 'owner';

    const CONDITION_FIRST_TIME_USE = 'FIRST_TIME_USE';
    const CONDITION_FIRST_TIME_USE_AFTER_REFURBISHMENT = 'FIRST_TIME_USE_AFTER_REFURBISHMENT';
    const CONDITION_MINT_CONDITION = 'MINT_CONDITION';
    const CONDITION_REFURBISHED = 'REFURBISHED';
    const CONDITION_PART_REFURBISHED = 'PART_REFURBISHED';
    const CONDITION_NEED_OF_REDEVELOPMENT = 'NEED_OF_REDEVELOPMENT';
    const CONDITION_DERELICT = 'DERELICT';
    const CONDITION_MODERNIZED = 'MODERNIZED';
    const CONDITION_FULLY_RENOVATED = 'FULLY_RENOVATED';
    const CONDITION_PART_RENOVATED = 'PART_RENOVATED';
    const CONDITION_WELL_KEPT = 'WELL_KEPT';
    const CONDITION_NEED_OF_RENOVATION = 'NEED_OF_RENOVATION';
    const CONDITION_NEGOTIABLE = 'NEGOTIABLE';
    const CONDITION_RIPE_FOR_DEMOLITION = 'RIPE_FOR_DEMOLITION';

    const OBJECT_TYPE_APARTMENT = 'APARTMENT';
    const OBJECT_TYPE_HOUSE = 'HOUSE';
    const OBJECT_TYPE_TRADE_SITE = 'TRADE_SITE';
    const OBJECT_TYPE_GARAGE = 'GARAGE';
    const OBJECT_TYPE_SHORT_TERM_ACCOMODATION = 'SHORT_TERM_ACCOMODATION';
    const OBJECT_TYPE_OFFICE = 'OFFICE';
    const OBJECT_TYPE_GASTRONOMY = 'GASTRONOMY';
    const OBJECT_TYPE_INDUSTRY = 'INDUSTRY';
    const OBJECT_TYPE_STORE = 'STORE';
    const OBJECT_TYPE_SPECIAL_PURPOSE = 'SPECIAL_PURPOSE';
    const OBJECT_TYPE_INVESTMENT = 'INVESTMENT';

    const OBJECT_SUBTYPE_ROOF_STOREY = 'ROOF_STOREY';
    const OBJECT_SUBTYPE_LOFT = 'LOFT';
    const OBJECT_SUBTYPE_MAISONETTE = 'MAISONETTE';
    const OBJECT_SUBTYPE_PENTHOUSE = 'PENTHOUSE';
    const OBJECT_SUBTYPE_TERRACED_FLAT = 'TERRACED_FLAT';
    const OBJECT_SUBTYPE_GROUND_FLOOR = 'GROUND_FLOOR';
    const OBJECT_SUBTYPE_APARTMENT = 'APARTMENT';
    const OBJECT_SUBTYPE_RAISED_GROUND_FLOOR = 'RAISED_GROUND_FLOOR';
    const OBJECT_SUBTYPE_HALF_BASEMENT = 'HALF_BASEMENT';
    const OBJECT_SUBTYPE_ATTIKA = 'ATTIKA';
    const OBJECT_SUBTYPE_OTHER = 'OTHER';
    const OBJECT_SUBTYPE_SINGLE_FAMILY_HOUSE = 'SINGLE_FAMILY_HOUSE';
    const OBJECT_SUBTYPE_TWO_FAMILY_HOUSE = 'TWO_FAMILY_HOUSE';
    const OBJECT_SUBTYPE_TERRACE_HOUSE = 'TERRACE_HOUSE';
    const OBJECT_SUBTYPE_MID_TERRACE_HOUSE = 'MID_TERRACE_HOUSE';
    const OBJECT_SUBTYPE_TERRACE_END_HOUSE = 'TERRACE_END_HOUSE';
    const OBJECT_SUBTYPE_END_TERRACE_HOUSE = 'END_TERRACE_HOUSE';
    const OBJECT_SUBTYPE_MULTI_FAMILY_HOUSE = 'MULTI_FAMILY_HOUSE';
    const OBJECT_SUBTYPE_TOWNHOUSE = 'TOWNHOUSE';
    const OBJECT_SUBTYPE_FINCA = 'FINCA';
    const OBJECT_SUBTYPE_BUNGALOW = 'BUNGALOW';
    const OBJECT_SUBTYPE_FARMHOUSE = 'FARMHOUSE';
    const OBJECT_SUBTYPE_SEMIDETACHED_HOUSE = 'SEMIDETACHED_HOUSE';
    const OBJECT_SUBTYPE_VILLA = 'VILLA';
    const OBJECT_SUBTYPE_CASTLE_MANOR_HOUSE = 'CASTLE_MANOR_HOUSE';
    const OBJECT_SUBTYPE_SPECIAL_REAL_ESTATE = 'SPECIAL_REAL_ESTATE';
    const OBJECT_SUBTYPE_TWIN_SINGLE_FAMILY_HOUSE = 'TWIN_SINGLE_FAMILY_HOUSE';
    const OBJECT_SUBTYPE_TRADE_SITE = 'TRADE_SITE';
    const OBJECT_SUBTYPE_GARAGE = 'GARAGE';
    const OBJECT_SUBTYPE_STREET_PARKING = 'STREET_PARKING';
    const OBJECT_SUBTYPE_CARPORT = 'CARPORT';
    const OBJECT_SUBTYPE_DUPLEX = 'DUPLEX';
    const OBJECT_SUBTYPE_CAR_PARK = 'CAR_PARK';
    const OBJECT_SUBTYPE_UNDERGROUND_GARAGE = 'UNDERGROUND_GARAGE';
    const OBJECT_SUBTYPE_DOUBLE_GARAGE = 'DOUBLE_GARAGE';
    const OBJECT_SUBTYPE_OFFICE_LOFT = 'OFFICE_LOFT';
    const OBJECT_SUBTYPE_STUDIO = 'STUDIO';
    const OBJECT_SUBTYPE_OFFICE = 'OFFICE';
    const OBJECT_SUBTYPE_OFFICE_FLOOR = 'OFFICE_FLOOR';
    const OBJECT_SUBTYPE_OFFICE_BUILDING = 'OFFICE_BUILDING';
    const OBJECT_SUBTYPE_OFFICE_CENTRE = 'OFFICE_CENTRE';
    const OBJECT_SUBTYPE_OFFICE_STORAGE_BUILDING = 'OFFICE_STORAGE_BUILDING';
    const OBJECT_SUBTYPE_SURGERY = 'SURGERY';
    const OBJECT_SUBTYPE_SURGERY_FLOOR = 'SURGERY_FLOOR';
    const OBJECT_SUBTYPE_SURGERY_BUILDING = 'SURGERY_BUILDING';
    const OBJECT_SUBTYPE_COMMERCIAL_CENTRE = 'COMMERCIAL_CENTRE';
    const OBJECT_SUBTYPE_LIVING_AND_COMMERCIAL_BUILDING = 'LIVING_AND_COMMERCIAL_BUILDING';
    const OBJECT_SUBTYPE_OFFICE_AND_COMMERCIAL_BUILDING = 'OFFICE_AND_COMMERCIAL_BUILDING';
    const OBJECT_SUBTYPE_BAR_LOUNGE = 'BAR_LOUNGE';
    const OBJECT_SUBTYPE_CAFE = 'CAFE';
    const OBJECT_SUBTYPE_CLUB_DISCO = 'CLUB_DISCO';
    const OBJECT_SUBTYPE_GUESTS_HOUSE = 'GUESTS_HOUSE';
    const OBJECT_SUBTYPE_TAVERN = 'TAVERN';
    const OBJECT_SUBTYPE_HOTEL = 'HOTEL';
    const OBJECT_SUBTYPE_HOTEL_RESIDENCE = 'HOTEL_RESIDENCE';
    const OBJECT_SUBTYPE_HOTEL_GARNI = 'HOTEL_GARNI';
    const OBJECT_SUBTYPE_PENSION = 'PENSION';
    const OBJECT_SUBTYPE_RESTAURANT = 'RESTAURANT';
    const OBJECT_SUBTYPE_SHOWROOM_SPACE = 'SHOWROOM_SPACE';
    const OBJECT_SUBTYPE_SHOPPING_CENTRE = 'SHOPPING_CENTRE';
    const OBJECT_SUBTYPE_FACTORY_OUTLET = 'FACTORY_OUTLET';
    const OBJECT_SUBTYPE_DEPARTMENT_STORE = 'DEPARTMENT_STORE';
    const OBJECT_SUBTYPE_KIOSK = 'KIOSK';
    const OBJECT_SUBTYPE_STORE = 'STORE';
    const OBJECT_SUBTYPE_SELF_SERVICE_MARKET = 'SELF_SERVICE_MARKET';
    const OBJECT_SUBTYPE_SALES_AREA = 'SALES_AREA';
    const OBJECT_SUBTYPE_SALES_HALL = 'SALES_HALL';
    const OBJECT_SUBTYPE_RESIDENCE = 'RESIDENCE';
    const OBJECT_SUBTYPE_FARM = 'FARM';
    const OBJECT_SUBTYPE_HORSE_FARM = 'HORSE_FARM';
    const OBJECT_SUBTYPE_VINEYARD = 'VINEYARD';
    const OBJECT_SUBTYPE_REPAIR_SHOP = 'REPAIR_SHOP';
    const OBJECT_SUBTYPE_LEISURE_FACILITY = 'LEISURE_FACILITY';
    const OBJECT_SUBTYPE_COMMERCIAL_UNIT = 'COMMERCIAL_UNIT';
    const OBJECT_SUBTYPE_INDUSTRIAL_AREA = 'INDUSTRIAL_AREA';
    const OBJECT_SUBTYPE_SPECIAL_ESTATE = 'SPECIAL_ESTATE';
    const OBJECT_SUBTYPE_INVEST_FREEHOLD_FLAT = 'INVEST_FREEHOLD_FLAT';
    const OBJECT_SUBTYPE_INVEST_SINGLE_FAMILY_HOUSE = 'INVEST_SINGLE_FAMILY_HOUSE';
    const OBJECT_SUBTYPE_INVEST_MULTI_FAMILY_HOUSE = 'INVEST_MULTI_FAMILY_HOUSE';
    const OBJECT_SUBTYPE_INVEST_LIVING_BUSINESS_HOUSE = 'INVEST_LIVING_BUSINESS_HOUSE';
    const OBJECT_SUBTYPE_INVEST_HOUSING_ESTATE = 'INVEST_HOUSING_ESTATE';
    const OBJECT_SUBTYPE_INVEST_MICRO_APARTMENTS = 'INVEST_MICRO_APARTMENTS';
    const OBJECT_SUBTYPE_INVEST_OFFICE_BUILDING = 'INVEST_OFFICE_BUILDING';
    const OBJECT_SUBTYPE_INVEST_COMMERCIAL_BUILDING = 'INVEST_COMMERCIAL_BUILDING';
    const OBJECT_SUBTYPE_INVEST_OFFICE_AND_COMMERCIAL_BUILDING = 'INVEST_OFFICE_AND_COMMERCIAL_BUILDING';
    const OBJECT_SUBTYPE_INVEST_SHOP_SALES_FLOOR = 'INVEST_SHOP_SALES_FLOOR';
    const OBJECT_SUBTYPE_INVEST_SUPERMARKET = 'INVEST_SUPERMARKET';
    const OBJECT_SUBTYPE_INVEST_SHOPPING_CENTRE = 'INVEST_SHOPPING_CENTRE';
    const OBJECT_SUBTYPE_INVEST_RETAIL_PARK = 'INVEST_RETAIL_PARK';
    const OBJECT_SUBTYPE_INVEST_HOTEL = 'INVEST_HOTEL';
    const OBJECT_SUBTYPE_INVEST_BOARDING_HOUSE = 'INVEST_BOARDING_HOUSE';
    const OBJECT_SUBTYPE_INVEST_SURGERY_BUILDING = 'INVEST_SURGERY_BUILDING';
    const OBJECT_SUBTYPE_INVEST_CLINIC = 'INVEST_CLINIC';
    const OBJECT_SUBTYPE_INVEST_ASSISTED_LIVING = 'INVEST_ASSISTED_LIVING';
    const OBJECT_SUBTYPE_INVEST_COMMERCIAL_CENTRE = 'INVEST_COMMERCIAL_CENTRE';
    const OBJECT_SUBTYPE_INVEST_HALL_STORAGE = 'INVEST_HALL_STORAGE';
    const OBJECT_SUBTYPE_INVEST_INDUSTRIAL_PROPERTY = 'INVEST_INDUSTRIAL_PROPERTY';
    const OBJECT_SUBTYPE_INVEST_CAR_PARK = 'INVEST_CAR_PARK';
}
